### PR TITLE
Don't worry if the first comment's not a doc comment; Add support for lunamark

### PR DESCRIPTION
**Pull request by geoffleyland**
As the title says.  I can't see any downside to not requiring the first comment to be a doc comment, but there might well be.

### CODE REVIEW

**Comment by hishamhm** [comment]
Perhaps it's a good idea to run through the list PRs and close the ones that were implemented, like this one?

**Comment by geoffleyland** [comment]
Yes!  This is so old that I can't remember what happened to it, but from what you say this has either been merged or superseded?  I'm happy for it to be closed, or to close it.

**Comment by stevedonovan** [comment]
Mea culpa - time for a new release, gents!

**Comment by alerque** [comment]
As far as I can make out this has been addressed and these commits are obsolete. If there is something I've missed and still needs fixing please let me know.

**Pull request closed without merging**
