### PR TITLE
Update markup.lua

### PR DESCRIPTION
**Pull request by alejandro-alzate**
Fixed: `/usr/local/share/lua/5.1/ldoc/markup.lua:159: attempt to index local 'line' (a nil value)`
By adding a check enclosing all the lines that play with `line` making sure is not `nil`

I Don't know exactly why is being triggered but i hope it helps.

### CODE REVIEW

**Comment by alerque** [comment]
For future reference next time don't close PRs, just continue making amend commits in the same branch.

**Comment by alejandro-alzate** [comment]
> For future reference next time don't close PRs, just continue making amend commits in the same branch.

Please excuse me
I realized that too late, when i did the other one, should i reopen it? if so how i can delete the other one? (#405)

**Comment by alerque** [comment]
No worries, you live and learn. Since you already have the other one open (and there is no delete) we'll just close this one and more on with review in the other one.

**Comment by alejandro-alzate** [comment]
you:
> you live and learn
my bio:
> open to help and get helped

Yeah last time I teached a translator how to rename a pr.

**Pull request closed without merging**
