### PR TITLE
fixes #255

### LINKED ISSUE #255: MoonScript `self` references are counted as "malformed"
Malformed reference when trying to use `\` in a reference in a MoonScript class. Patch below.

```diff
diff --git a/ldoc/doc.lua b/ldoc/doc.lua
index e19b2df..7015482 100644
--- a/ldoc/doc.lua
+++ b/ldoc/doc.lua
@@ -1098,7 +1098,7 @@ function Module:process_see_reference (s,modules,istype)
    local mod_ref,fun_ref,name,packmod
    local ref = custom_see_references(s)
    if ref then return ref end
-   if not s:match '^[%w_%.%:%-]+$' or not s:match '[%w_]$' then
+   if not s:match '^[%w_%.\\%:%-]+$' or not s:match '[%w_]$' then
       return nil, "malformed see reference: '"..s..'"'
    end

```

How to apply diff:

```sh
git apply << EOF
diff --git a/ldoc/doc.lua b/ldoc/doc.lua
index e19b2df..7015482 100644
--- a/ldoc/doc.lua
+++ b/ldoc/doc.lua
@@ -1098,7 +1098,7 @@ function Module:process_see_reference (s,modules,istype)
    local mod_ref,fun_ref,name,packmod
    local ref = custom_see_references(s)
    if ref then return ref end
-   if not s:match '^[%w_%.%:%-]+$' or not s:match '[%w_]$' then
+   if not s:match '^[%w_%.\\\\%:%-]+$' or not s:match '[%w_]$' then
       return nil, "malformed see reference: '"..s..'"'
    end

EOF
```

### PR DESCRIPTION
**Pull request by nonchip**

### CODE REVIEW

**Comment by nonchip** [comment]
note: for some unknown reason ldoc still complains about the function not being found, while generating the correct output

**Comment by Lukc** [comment]
Using the form `-- @see Class\method` works fine.

Could this get merged ASAP? It’s pretty much critical if anyone is to use LDoc to document Moonscript…

**Comment by nonchip** [comment]
that, combined with @stevedonovan's speed when merging nonconflicting important PRs is why i now made and switched to https://github.com/cuddlyrobot/lunadoc/, which does moonscript right (by using the moonscript parser instead of misinterpreting regexes).

**Comment by Lukc** [comment]
It looks like an interesting project.

I might very well switch to it in the near future if LDoc remains stagnant or if lunadoc becomes more complete and documented. :)
I’m not doing it right away because I spent half of the day tweaking an LDoc template. I don’t want to do that work again unless there are significant benefits. :p

**Comment by nonchip** [comment]
very understandable. lunadoc is pretty young yet, but will be growing with my documentation needs, for example I'm currently working to support more in-depth commenting of tables (which i currently completely ignore, it currently just matches functions and classes and their properties and members), including moonscript files that are just implicitly returning tables (e.g. for a `config.moon` file documentation etc).

**Comment by Lukc** [comment]
To give an idea of the level of complexity I need in my documentation and for further reference, here’s the current output of a project I’m working on through LDoc:

> http://lukc.upyum.com/pkgxx/index.xhtml
> http://lukc.upyum.com/pkgxx/classes/Recipe.xhtml

The sources of everything are stored here:

> https://github.com/Lukc/pkgxx

Things got messy at some point. O:)

**Comment by nonchip** [comment]
most of the stuff I see there at first glance (except distinction between modules and scripts, and lack of file-based documentation; currently you'd have to move that to the class doc block) would already work, but yeah, if I was you I'd wait, because I'm pretty sure I'll make some api breaking changes in lunadoc at some point soon and you don't want to rewrite everything twice :P

**Comment by alerque** [comment]
Thanks for taking the time to contribute @nonchip. I'm not exactly sure what I'm testing here. I'm happy to merge a fix to accommodate Moonscript, but I'm having trouble knowing what to check to make sure I'm not breaking plain Lua in the process. What is a use case that I can test this with?

**Review by alerque — COMMENTED** [review]
Thanks for taking the time to contribute @nonchip. I'm not exactly sure what I'm testing here. I'm happy to merge a fix to accommodate Moonscript, but I'm having trouble knowing what to check to make sure I'm not breaking plain Lua in the process. What is a use case that I can test this with?

**Comment by s-ol** [comment]
@alerque it's been a while, but iirc this just allows using the form `class\method` in documentation links when using MoonScript. It might also be that without this moonscript just errors out completely because it generates some such links itself internally, but I don't know anymore.

**Comment by alerque** [comment]
Thanks. With those comments in mind I've had another look ath this, and I think I've made sense of it. Actually what is confusing me more than anything is not the addition of a backslash `\` (escaped because of the string it's in) but why the colon character in that set is escaped as if it was a Lua Pattern magic character! Additionally the second pattern match doesn't make sense because the first one should already cover it.

However whatever those are about, it is that way already so merging this shouldn't hurt.

**Pull request merged**
